### ISSUE TITLE
Valider le Logo du GT

### ISSUE THREAD

**Issue by gcebelieu** [cnigfr/Geostandards-Risques#1]
Un logo est associé au GT Géoqtandards Risques.

Le CNIG nous propose celui ci : ![logo GT CNIG](http://cnig.gouv.fr/wp-content/uploads/2021/12/risq.png).

Nous pouvons l'adopter s'il nous convient, ou en proposer d'autres.

**Comment by gcebelieu** [comment]
Propositions alternatives faites par la DGPR/DAGSI : 

1. Proposition 1  ![logo-GT-propDGPR-1](https://user-images.githubusercontent.com/8211614/149284197-5bac298c-5dae-4ff8-a8ff-80c43bcc94fc.jpg)

2. Proposition 2  ![logo-GT-propDGPR-2](https://user-images.githubusercontent.com/8211614/149284301-3e886533-3459-48dc-b5d2-271f7b269a53.jpg)

**Comment by GT-CNIG-DDU** [comment]
Le logo du standard COVADIS était bien :

![Logo standard Covadis](https://user-images.githubusercontent.com/79853274/149469840-bca1dabc-9cac-4da4-9c19-4bff80f8000e.jpg)

**Comment by GuillaumeChretien** [comment]
Préférence pour celui proposé par le CNIG
