### ISSUE TITLE
Question sur le lien des Géostandards Risques avec les PPI (Plans particuliers d’intervention)

### ISSUE THREAD

**Issue by gcebelieu** [cnigfr/Geostandards-Risques#10]
Je relaye cette question posée par un opérateur national de réseau : 

> En tant qu’opérateur de réseau intervenant sur le territoire national nous sommes en train de chercher une solution pour obtenir les PPI liés aux installations classées.
> Nous cherchons à nous appuyer sur l’organisation ORSEC mais les travaux que vous entreprenez dans le GT ci-dessous pourraient-ils couvrir aussi les PPI ?

Mon avis est que le périmètre des standards risques est celui des données de prévention (description du risque) et ne couvre donc pas les plans de gestion de crise. Cependant, le lien entre les deux me semble pertinent. Y a-t-il lieu d'étudier les dépendances entre les données de risques et ce type de plan ?

**Comment by magalidisalvo** [comment]
bonjour
je pense que c'est hors périmètres d'autant que les PPI ne sont absolument pas standardisés et souvent, pas numérisés ; ça pourrait faire l'objet d'un GT CNIG spécifique

**Comment by GuillaumeChretien** [comment]
Un standard serait approprié mais les PPI relèvent du ministère de l'intérieur, il semblerait plus approprié de dissocier un standard prévention / connaissance d'un standard intervention gestion de crise. Les cercles PPI détaillées sont particulièrement sensibles, en général seules les grands cercles agrégées sont diffusées (plaquettes grand public).
Pour les risques techno le lien est surtout "origine risque".

**Comment by gcebelieu** [comment]
Je ferme cette issue (pas d'actions supplémentaires à effectuer à priori sur le sujet). Elle pourra être réouverte si le sujet devait revenir sur la table dans le cadre du GT.
