### ISSUE TITLE
Ventiler les classes existantes dans les thématiques métiers identifiées

### ISSUE THREAD

**Issue by gcebelieu** [cnigfr/Geostandards-Risques#3]
Il s'agit redistribuer les classes de standards existants (à refondre, en adhérence ou dans le thème) identifiés en #2 dans les nouvelles thématiques métiers ébauchées lors de l'étude préalable.  

C'est un travail préparatoire pour la refonte qui permettra de :
- Valider la définition des thématiques métiers ébauchées lors de l'étude préalable
- S'approprier les standards existants
- Identifier les redondances entre standards (et donc anticiper des d'harmonisations à mettre en œuvre pour la rédaction des nouveaux standards)

Plusieurs ateliers sont à prévoir (pour chaque standard existant, certains éventuellement regroupés)

**Comment by GuillaumeChretien** [comment]
Pourrait-on pour chaque standard existant mettre un jeu de données sur le git qui puisse servir d'exemple concret ? Cela permettrait par exemple sur un même territoire de comparer l'ancien COVADIS, le CNIG SUP pour des PPR (N et T) et d'échanger entre nous sur une même base avec qgis en fond pour explorer la données.

**Comment by benoitdavidfr** [comment]
Attention, l'approche choisie de travailler directement sur les classes des standards existants peut être difficile à appréhender par les personnes qui connaissent le métier mais ne sont pas habituées aux démarche de modélisation. Cela peut avoir pour conséquence de les exclure de la discussion sur le périmètre des standards, qui visiblement est un point délicat.
Ne faudrait-il pas plutôt procéder comme si un nouveau standard est créé ?

**Comment by GT-CNIG-DDU** [comment]
@GuillaumeChretien les données SUP sont téléchargeables depuis le Géoportail de l'urbanisme.
Menu [Recherche avancée](https://www.geoportail-urbanisme.gouv.fr/search-document/) et taper PM1 ou PM3 dans la rubrique titre. Pour le lot sélectionné, l'icône télécharger est ensuite à droite de l'écran.
Ceci peut effectivement contribuer à constituer un lot de données test.

**Comment by gcebelieu** [comment]
> Attention, l'approche choisie de travailler directement sur les classes des standards existants peut être difficile à appréhender par les personnes qui connaissent le métier mais ne sont pas habituées aux démarche de modélisation. Cela peut avoir pour conséquence de les exclure de la discussion sur le périmètre des standards, qui visiblement est un point délicat. Ne faudrait-il pas plutôt procéder comme si un nouveau standard est créé ?

@benoitdavidfr merci pour cette alerte, on va s'attacher à ne pas être trop abstrait dans cet atelier sans rentrer dans le détail des règles de modélisation. 
Cette action participe à la définition du périmètre des nouveaux standards mais je suis d'accord qu'elle ne doit pas être la seule et ne le sera pas. L'action #2 doit aussi permettre de rajouter d'autres éléments à intégrer et s'il n'y a pas de modélisation spécifique derrière ces nouveaux éléments, on pourra toujours s'interroger si les thématiques métiers permettent de les intégrer.

**Comment by gcebelieu** [comment]
> Pourrait-on pour chaque standard existant mettre un jeu de données sur le git qui puisse servir d'exemple concret ? Cela permettrait par exemple sur un même territoire de comparer l'ancien COVADIS, le CNIG SUP pour des PPR (N et T) et d'échanger entre nous sur une même base avec qgis en fond pour explorer les données.

@GuillaumeChretien, @GT-CNIG-DDU , c'est une bonne idée de recenser des jeux de données existants, soit en les référençant s'ils sont accessibles en ligne, soit en les intégrant au dépôt sinon. 
Je propose de créer une rubrique "Jeux de données" dans la partie "documents" du dépôt pour faire ce recensement.

**Comment by StanBesson** [comment]
Bonjour,
dans la ventilation des classes existantes, il faudrait également intégrer les "ouvrages de protection" et "zones protégées"présents dans le standard DI mais absent du PPR.

**Comment by gcebelieu** [comment]
Bonjour,
Effectivement @StanBesson, ces deux classes ne sont pas dans le standard PPR et il faudrait voir si elles correspondent bien aux thématiques métiers discutées en atelier.

NB : Sur le "Mural", la classe "ouvrages de protection" est bien représentée pour le standard DI, par contre la classe "zone protégée" n'y apparait pas (elle n'était pas représentée sur le schéma du modèle conceptuel de la version 2.1 alors qu'elle apparait dans le dictionnaire) mais d'après sa définition, elle se substituerait à la classe "zone soustraite à l'inondation" de l'ancienne version DI qui y figure. J'ai rajouté un post-it sur le mural pour le préciser.

![image](https://user-images.githubusercontent.com/8211614/151797280-b25280e5-eb48-4a6d-8429-19a567803f33.png)

**Comment by gcebelieu** [comment]
La synthèse des discussions de l'atelier du 28/01 a été déposée [ici](https://github.com/cnigfr/Geostandards-Risques/blob/main/suivi/2022-01-28-Atelier-Thematiques-metiers-classes-TRI-PPR/2022-01-28-Synthese-Atelier-repartition-classes-thematiques.docx). Elle comprend notamment : 

- La révision des noms et des définitions de certaines thématiques, les points d’attention et les questionnements qui ont été levés (à noter l’ajout d’une nouvelle thématique dédiée à l’origine du risque)
- Les résultats intermédiaires des répartitions des classes des standards DI et PPR dans ces nouvelles thématiques à l’aide de l’outil collaboratif Mural. 

N’hésitez pas à faire part de vos remarques sur ces éléments. Ils seront présentés et discutés en plénière le 18/02.

Par ailleurs et en particulier pour ceux qui n’ont pu participer à l’atelier, vous pouvez toujours accéder au Mural via le lien présent dans le document et affecter les « pastilles » correspondant aux thématiques métiers  aux classes des standards DI et PPR qui y sont représentés.

**Comment by gcebelieu** [comment]
Proposition de fermer cette issue qui a contribué à l'élaboration du document de [Synthèse des travaux préliminaires du GT](https://github.com/cnigfr/Geostandards-Risques/blob/main/documents/Cadrage/CNIG_GT-Risques_Synthese-Cadrage-v1.0.docx?raw=true)

**Comment by gcebelieu** [comment]
Fermeture en plénière GT risques
