### ISSUE TITLE
Identifier les domaines à couvrir par les nouveaux standards

### ISSUE THREAD

**Issue by gcebelieu** [cnigfr/Geostandards-Risques#5]
Il s'agit de déterminer, ce qui sera à définir dans les nouveaux standards et élaborer un plan type pour la rédaction.

![Plan-type-standard](https://user-images.githubusercontent.com/8211614/149292827-bf8de310-026d-4e1a-9d18-e9e70ae08ffd.jpg)

**Comment by GT-CNIG-DDU** [comment]
Les rubriques "Qualité" et "Métadonnées" sont fortement recommandées pour les géostandards CNIG.
Le [GT CNIG QuadoGéo](http://cnig.gouv.fr/?page_id=18183) en a produit une trame "[Modèle pour les chapitres qualité et métadonnées des Géostandards](http://cnig.gouv.fr/wp-content/uploads/2021/10/211015-Mod%C3%A8le-de-parties-Qualit%C3%A9-et-M%C3%A9tadonn%C3%A9es-des-g%C3%A9ostandards.pdf)"

**Comment by benoitdavidfr** [comment]
Comme indiqué en réunion, vu le périmètre envisagé des standards, il me semble intéressant de reprendre la bonne pratique du Sandre en distinguant une partie dictionnaire de donnée d'une partie scenario d'échange, sachant qu'il peut exister plusieurs scenario d'échange par exemple un de diffusion, un autre de dépôt de documents, ...
L'objectif du GT pourrait être de définir la partie dictionnaire de données ainsi que les scenarios d'échange les plus évidents en laissant la possibilité de définir de nouveaux scenarios d'échange pour d'autres besoins.

**Comment by gcebelieu** [comment]
Lien vers le "mural" collaboratif. Les premiers éléments de synthèse sont dans les post-it ronds en vert.

https://app.mural.co/t/ign6805/m/ign6805/1644943331129/a225e8090f3efe55df7175655229630d3e7ab013?sender=u7cb5d16a155aefd8d9423388

**Comment by gcebelieu** [comment]
Proposition de fermer cette issue qui a contribué à l'élaboration du document de [Synthèse des travaux préliminaires du GT](https://github.com/cnigfr/Geostandards-Risques/blob/main/documents/Cadrage/CNIG_GT-Risques_Synthese-Cadrage-v1.0.docx?raw=true)

**Comment by gcebelieu** [comment]
Fermeture en plénière GT risques
