### ISSUE TITLE
Statuer sur la licence de diffusion des nouveaux standards

### ISSUE THREAD

**Issue by gcebelieu** [cnigfr/Geostandards-Risques#6]
Il s'agit de déterminer les droits d’accès de diffusion à appliquer aux documents finaux ?

En se posant éventuellement les questions suivantes :  
- Quelles sont les attentes de la DGPR ?
- Quelles licences s’appliquent aux standards existants ?
- Y a-t-il une politique particulière pour les standards CNIG ?
- Quelles sont les licences existantes / appropriées pour ce genre de documents ?

**Comment by GT-CNIG-DDU** [comment]
Les géostandards CNIG ne sont-ils pas sous [Licence ouverte Etalab 2.0](https://www.etalab.gouv.fr/licence-ouverte-open-licence) ?
Les géostandards CNIG d'urbanisme, accessibilité du cheminement, continuités écologiques régionales, etc. sont publiés sous cette licence.

**Comment by benoitdavidfr** [comment]
Je suis d'accord, la licence ouverte 2.0 me semble adaptée.

**Comment by magalidisalvo** [comment]
D'accord aussi avec la licence ouverte etalab sous paternité CNIG

**Comment by gcebelieu** [comment]
Cf. CR de la plénière du 18/02 : https://github.com/cnigfr/Geostandards-Risques/blob/main/suivi/2022-02-18-Pleniere-GT/220218_SPP-22-0400_CR_R%C3%A9union_Pl%C3%A9ni%C3%A8re_20220325.pdf 

> 
> La proposition est de reprendre de le modèle SUP CNIG avec l’**application de la licence ouverte, d’indiquer que le standard appartient au CNIG, de mentionner la DGPR (maitrise d’ouvrage) et l’ensemble des participants du GT dans les sources et les contributeurs.**
> La proposition est acceptée en notant qu’il faudra faire attention à **faire la distinction au niveau des contributeurs entre les rédacteurs du standard (droits d’auteurs) et les relecteurs parmi les membres du GT.**

**Comment by GT-CNIG-DDU** [comment]
Pour info, le GT CNIG QuaDoGéo met à disposition un "[Modèle des chapitres Qualité et Métadonnées des géostandards](http://cnig.gouv.fr/wp-content/uploads/2021/10/211015-Mod%C3%A8le-de-parties-Qualit%C3%A9-et-M%C3%A9tadonn%C3%A9es-des-g%C3%A9ostandards.pdf)"
