### ISSUE TITLE
Ajout du type d'aléa "Indifférencié"

### ISSUE THREAD

**Issue by tportier** [cnigfr/Geostandards-Risques#71]
Bonjour,

Il semblerait que dans la nouvelle version du standard pour les PPRI, le niveau d'aléa "Indifférencié" ne soit pas pris en compte. Les couches d'aléas actuelles intègre cette notion. 

Merci

**Comment by gcebelieu** [comment]
Bonjour, merci pour votre question. 

Effectivement ce niveau d'aléa "indifférencié" ne figure pas dans la nouvelle version. A ma connaissance, il n'en est pas fait mention dans les différents guides méthodologiques PPR utilisés pour cette nouvelle version. 

Pouvez-vous indiquer des références documentaires qui permettraient de qualifier ce niveau d'aléa et de voir si on peut le prendre en compte dans le nouveau standard PPR (encore en cours d'élaboration).

Merci par avance

**Comment by gcebelieu** [comment]
Après discussion avec le Groupe de travail, ce niveau d'aléa ne fait pas partie des niveaux d'aléas connus du risque d'inondation (cf. #73) . Je ferme donc cette issue.
